



.model small

.stack 256



.data



;========================Variables declaradas aqui===========================
var 	dW 3		;VARIABLES TIPO WORD(16 BITS)
var1 	dW 10			
var2 	dW 7
var3	dW 8
var4 	dW 9		
var5 	dW 2
var6	dW 1
var7	dW 12	
var8 	dW 15
var9	dW 4

;BUFFER  DB   10 DUP (0)

BUFFER 	DB   0
		DB	 0
		DB 	 0
		DB   0
		DB   0
		DB   0
		DB   0
		DB   0
		DB   0
		DB   0







;============================================================================

.code
main:	
	mov ax,@data
	mov ds,ax
	mov es, ax                  ;set segment register
    and sp, not 3               ;align stack to avoid AC fault

	
;====================================Código==================================  


;----------------------------------------------------------------------------------------------------------------------- VALOR 0

MOV BX,VAR				;TOMO EL PRIMER OPERANDO
MOV AX,1000				;ASIGNNO VALOR DE OPERACION INICIAL
SUB AX,BX				;RESTO AL MIL LA PRIMERA VARIABLE
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO					;SI <=9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 1

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR1 			;AX-VAR1
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM1					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM1:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE1				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE1:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO1					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO1:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 2

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR2				;AX-VAR2
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM2				;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM2:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE2				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE2:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO2					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO2:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 3

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR3				;AX-VAR3
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM3					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM3:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE3				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE3:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO3					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO3:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 4

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR4				;AX-VAR4
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM4					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM4:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE4				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE4:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO4					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO4:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 5

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR5				;AX-VAR5
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM5					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM5:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE5				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE5:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO5					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO5:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 6

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR6				;AX-VAR6
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM6					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM6:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE6				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE6:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO6					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO6:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 7

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR7				;AX-VAR7
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM7					;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM7:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN EXADECIMAL TIENE 2 CIFRAS
JLE SLE7				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE7:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO7					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO7:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 8

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR8				;AX-VAR8
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM8				;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM8:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 2 CIFRAS
JLE SLE8				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE8:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO8					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO8:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,2DH 				;IMPRIMIR GUION
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,2DH 				;IMPRIMIR GUION
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,2DH 				;IMPRIMIR GUION
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

;----------------------------------------------------------------------------------------------------------------------- VALOR 9

MOV AX,DI 				;RECUPERO EL RESULTADO
SUB AX,VAR9				;AX-VAR9
MOV DI,AX				;SALVO EL RESULTADO

CMP DI,255				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 3 CIFRAS
JLE SIM9				;SI ES <=255 SALTA Y PASA A LAS DECENAS

SHR AX,08				; ME QUEDO CON EL PRIMER DIGITO
ADD AX,30H				; CONVIERTO A ASCII


MOV AH,02               ;EJECUTO FUNCION 02
MOV DL,AL				;TOMO CENTENA 
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SIM9:
MOV AX,DI				;RECUPERO EL RESULTADO
CMP DI,15				;COMPARO PARA VER SI EL NUMERO EN HEXADECIMAL TIENE 2 CIFRAS
JLE SLE9				;SI ES <=15 SALTA Y PASA A LA UNIDAD
AND AX, 00F0H			;FILTRO LA DECENA
SHR AX,4				;COLOCA LA DECENA EN LA POSICION INDICADA PARA CONVERTIR ASCII
ADD AX,55				;CONVIERTO A ASCII

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

SLE9:
MOV AX,DI				;RECUPERO EL RESULTADO
AND AX, 000FH			;FILTRO LA UNIDAD
CMP AX,9				;PARA VERIFICAR COMO DEBO DE AJUSTAR.
JNG KO9					;SI <9 SALTA,Y SUMA SOLO 30
ADD AX,7				;SI ES >9,SUMA 7 PARA PASAR A LOS CARACTERES EN MAYUSCULA
KO9:
ADD AX,30H				

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,AL				;TOMO CENTENA
INT 21H					;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA

MOV AH,02				;EJECUTO LA FUNCION 02
MOV DL,0AH 				;SALTO DE LINEA
INT 21h 				;ENVIO EL CARACTER AL DISPOSITIVO DE SALIDA











;============================================================================

.exit
;================================Funciones aqui==============================






;============================================================================
end main
